apiVersion: v1
kind: Service
metadata:
    name: lakavathgouthamipipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 8443 
    selector:
        app: lakavathgouthamipipelinesjavascriptdocker
